### PR TITLE
bdPluginStorage -> BdApi

### PR DESCRIPTION
**Pull request by Gusted**
It's has been Deprecated BdApi.setData() and BdApi.getData() Is the newer functions

Related issue #3

### CODE REVIEW

**Review by Technetium1 — APPROVED** [review]
LGTM

**Comment by Technetium1** [comment]
This should probably bump the version number @Gusted

**Review by ykonyshev — APPROVED** [review]
Thanks! Made the plugin work again!

**Comment by Technetium1** [comment]
@kosshishub don't forget to test and merge someday :)

**Comment by kosshi-net** [comment]
> @kosshishub don't forget to test and merge someday :)

I'm unable to test since I do not use BetterDiscord (or Discord at all) anymore, but this seems safe enough :) 

Thank you.

**Pull request merged**
